config/routes.rb
Rails.application.routes.draw do
  # root 'public#index'
  # devise_for :users
  root 'home#index'
  # get 'home/index'
  get 'home/videos'
  get 'home/careers'
  # , to: 'home#about'
  get 'home/our_mission'
  get 'home/gallery'
  
  # get 'careers/new'

  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    confirmations: 'devise/confirmations', sign_up_create: 'home'
  }
  
  # to verride registrations controller 
  # devise_for :users, controllers: {registrations: 'users/registrations',
  #   confirmations: 'devise/confirmations', sign_up_create: 'home'
  # }
  resources :dashboard
  resources :home, only: [:index, :our_mission, :about]
  
  resources :user do 
   resources :project 
  end
  

  resources :careers, :only => [:show, :new, :create]
  
devise_scope :user do
  get "/users/sign_out" => "devise/sessions#destroy"
end
  # get 'users/sign_out', to: 'devise/sessions#destroy'

  # post "/dashboard", to: "sign_up_create#update"


  #not using /users route
  # get '/users', to: 'users#index'
  # devise_for :users, controllers: {sessions: 'devise/sessions', users: 'users'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  #  list of users ?
  # get 'users#sign_up'
  # get 'users#sign_in'
  # get '/'
  # get '/sign'
  # get 'devise/sessions#new'
  # get '/users/sign_up'

  # new devise registrations//missing controller?
  # registration page route?
  # get 'devise/registrations/index'

  # get 'devise/registrations#new'
  # (.:format) 
  # get 'dashboard/index'
  # post 'dashboard/index'

  # get '/dashboard/new'
  # get 'dashboard/show'
  # get 'dashboard/edit'
  # post 'dashboard/create'
  # post 'dashboard/update',  to 'dashboard#update'

  # not using users page
  # get 'users/index'

  resources :sign_up_create
  
  # post "/signupcreate", to: "sign_up_create#create"

  # resdaer
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'dashboard#index'
  


# get '/users/:user', to: 'devise/sessions#sign_in', as: 'user'

# get '/users/:user', to: 'devise/sessions#destroy'
# , as: 'user'

# resource :users
# unauthenticated do
  # root to: "home#index"
# end
# authenticated do 
  # root :to => 'dashboard#index'
# end

# as :user do
  # get 'sign_in', :to => 'devise/sessions#new'
  # get 'sign_out', :to => 'devise/sessions#destroy'
# end

#  get '/users/:username', to: 'sessions#show' 
#  get '/users/:username', to: 'sessions#show', as: 'user'
# controllers {sessionsController}
# get '/users/new' controllers { sessionsController}
end

app/views/shared/_cost.html.erb
<%# <div class="h-auto bg-transparent border-2 border-blue-700"> %>
  <div class="w-[95%] md:w-[90%] rounded-3xl max-w-[1200px] mt-10 m-auto lg:mt-16 bg-blue-700 shadow-2xl">
    <%= image_tag("no-bg-elements/wall-labeled-nobg.png", alt: "reinforced concrete wall model illustration labeled", class: 'w-[90%] self-center m-auto lg:w-full max-w-[600px] 2xl:w-full 2xl:h-44 object-cover', id:"concrete-wall-image", :style => "") %>
    
    <div class="mt-10 bg-white dark:bg-gray-600 pb-6 shadow-2xl rounded-b-3xl">
      <h2 class="text-center text-gray-800 dark:text-gray-300 text-lg md:text-xl lg:text-2xl font-bold pt-6"> Reinforced Concrete Retaining Wall Cost </h2>
      <h4 class="text-center text-gray-400 dark:text-gray-300 text-md md:text-lg lg:text-xl font-bold pt-2">(With footer already poured)</h4>
    
      <div class="w-5/6 h-[100px] m-auto relative">
        <span class="bubble motion-safe:animate-floatX left-0 top-1 bg-gray-600 dark:bg-gray-200 dark:text-gray-600 text-gray-100">20,000 psi strength</span>
        <br>
        <span class="bubble motion-safe:animate-floatX bg-gray-500 top-1 left-[40%] text-gray-100">Highest quality materials</span>
        <br>
        <span class="bubble motion-safe:animate-floatX left-[unset] right-0 top-1 bg-gray-400 text-gray-100">Built to Last</span>
        <p class="hidden text-center">You can now listen to millions of songs, audiobooks ands podcasts on any device anywhere you like!</p>
      </div>
      <div class="grid grid-cols-4 w-72 lg:w-3/6 m-auto bg-indigo-50 mt-5 p-4 lg:p-4 rounded-2xl ">
        <div class="col-span-1">
          <%= image_tag("icons/work-3d.png", alt: "work icon", class: 'w-15 lg:w-12', id:"concrete-wall-image", :style => "") %>
        </div>
        <div class="col-span-2 pt-1 ">
        
          <p class="text-gray-800 font-bold text-sm md:text-md lg:text-lg">Starting From</p>
          <p class="text-gray-500 text-xl md:text-2xl font-bold">$7.50 / ft²</p>
        </div>
        <div class="pt-2">
          <a href="#see-more" class="text-indigo-700 underline hover:no-underline  text-sm hover:text-indigo-500 font-bold">See more</a>
        </div>
      </div>
      <div class="bg-blue-700 w-72 lg:w-1/6 m-auto mt-6 md:mt-8 p-2 hover:bg-blue-500 rounded-2xl  text-white text-center shadow-xl shadow-bg-blue-700">
        <%# <button class=""> %>
         <%= link_to 'Schedule now', new_dashboard_url, class: 'lg:text-lg text-md font-bold' %>
        <%# </button> %>
      </div>
      <div class="hidden text-center m-auto mt-6 w-full h-16">
        <button class="hidden text-gray-500 font-bold lg:text-sm hover:text-gray-900">Cancel Order</button>
      </div>
    </div>
  </div>
<%# </div> %>

<%# javascript_pack_tag 'cost-partial' %>

app/views/shared/_featured.html.erb
<div class="mt-20 mb-10 rounded-3xl shadow-2xl shadow-gray-800 md:mt-10 w-[95%] md:w-[90%] max-w-[1200px] mx-auto">
	<div class="w-[100%] relative py-8 border-2 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] bg-blue-500 dark:from-blue-700 dark:via-blue-800 dark:to-gray-900 rounded-3xl dark:bg-gray-800 dark:border-gray-700">
		<%# <a href="#"> %>
    <h3 class="mt-5 text-center text-slate-200 dark:text-slate-200 font-semibold text-lg md:text-xl lg:text-2xl tracking-tight">Featured project: Lake Village Welcome Center</h3>
    <h4 class="text-center text-md md:text-lg lg:text-xl  text-gray-400">(Lake Village, AR)</h4>

    <div id="container" data-action="click->hello#toggleFullscreen">
      <%= image_tag("retaining-wall-lake-village-finished-hd-cropped.png", alt: "Reinforced Concrete Retaining Wall finished project", class:"rounded-[3rem] p-4 w-[60%] h-auto max-w-[800px] m-auto opacity-1 ", id:"toggle-fullscreen", :style=> "") %>
    </div>
    <div class="px-5 pb-5">
      <h1 class="text-center font-bold text-gray-200 text-lg md:text-xl lg:text-2xl " style="z-index: 9;"><span class="text-gray-400 font-bold"></span>Commercial Project</h1>
    </div>
    <div class="flex flex-col gap-4 justify-center items-center mt-5 mb-10">
        <%# <svg class="w-5 h-5 text-yellow-300" fill="currentColor" viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg">
          <path
            d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z">
          </path>
        </svg>
        <svg class="w-5 h-5 text-yellow-300" fill="currentColor" viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg">
          <path
            d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z">
          </path>
        </svg>
        <svg class="w-5 h-5 text-yellow-300" fill="currentColor" viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg">
          <path
            d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z">
          </path>
        </svg>
        <svg class="w-5 h-5 text-yellow-300" fill="currentColor" viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg">
          <path
            d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z">
          </path>
        </svg>
        <svg class="w-5 h-5 text-yellow-300" fill="currentColor" viewBox="0 0 20 20"
          xmlns="http://www.w3.org/2000/svg">
          <path
            d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z">
          </path>
        </svg> %>
      <h3 class="text-gray-400 text-md md:text-lg lg:text-xl ">Total cost:</h3>
      <h2 class="bg-blue-100 text-blue-800 text-lg md:text-xl lg:text-2xl font-bold px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800" >$12.50 / ft²</h2>
        <h3 class="text-gray-400 text-md md:text-lg lg:text-xl">Total time:</h3>
      <h2 class="bg-blue-100 text-blue-800 text-lg md:text-xl lg:text-2xl  font-bold px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800" >8 weeks</h2>
      <span class="hidden bg-blue-100 text-blue-800 text-xs font-semibold mr-2 px-2.5 py-0.5 rounded dark:bg-blue-200 dark:text-blue-800 ml-3">5.0</span>
    </div>
      
    <%# link_to 'Schedule now', new_dashboard_url, class: 'new-project top-float' %>
    <span class="bubble motion-safe:animate-float first bg-blue-700 text-sm md:text-md lg:text-lg text-gray-100 p-4">200+ yrds in length</span>
    <span class="bubble second motion-safe:animate-float bg-blue-600 text-sm md:text-md lg:text-lg text-gray-100 p-4">Curved designed</span>
    <span class="bubble third motion-safe:animate-float bg-blue-500 text-sm md:text-md lg:text-lg text-gray-100 p-4">Supports commercial building</span>
    <span class="bubble fourth motion-safe:animate-float bg-blue-500 text-sm md:text-md lg:text-lg text-gray-100 p-4">Built to meet state specifications</span>
    <div class="hidden items-center justify-between">
      <span class="text-3xl font-bold text-gray-900 dark:text-white">$599</span>
      <a href="#"
        class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Add
        to cart</a>
    </div>
	</div>
</div>
<script>

</script>

app/views/shared/_header.html.erb
<script>
    window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 60 || document.documentElement.scrollTop > 60) {
    
    document.getElementById("navbar").classList.add('blurred-transparent')
      document.getElementById("navbar").classList.remove('navbar-background');
  } else {
   
     document.getElementById("navbar").classList.remove('blurred-transparent');
        document.getElementById("navbar").classList.add('navbar-background');
  }
}
</script> %>
   <nav id="navbar" class="navbar-res

   border-element
   <%# navbar-expand-md  %>
   <%# navbar-custom  %>
   <%# fixed-top  %>
   <%# justify-content-center  %>
   <%# align-content-center  %>
   <%# align-items-center %>
   "
     style="margin: auto;"
   >
   
    <!-- Text Logo - Use this if you don't have a graphic logo -->
    <div class="navbar-brand logo-image mt-1" 
      style="">
      <a href="<%= root_path %>" >
        <%= image_tag("logo/final-logos-nobg/logo-notitle-spaced-nobg.png", alt: "My logo", class: '', size: '75x75', :style => "padding-bottom: 5px;") %>

        <%= image_tag("logo/final-logos-nobg/logo-title-straight-black-red-nobg.png", alt: "Segura & Co Logo", class: '', :style => "padding: 0px 0px;") %>

      </a>    
      <% link_to 'SEGURA & Company', root_path, class:"nav-title" %>

      <button class="hamburger hamburger--elastic 
        hidden" type="button"
        aria-label="Menu" aria-controls="navigation">
        <span class="hamburger-box">
          <span class="hamburger-inner"></span>
        </span>
      </button>
    </div>  
    <div class="button hidden">
    </div>
    <ul class="navbar-nav-res"
        <%# style="border:2px dashed yellow; " %>
      >

        <%# <li class="nav-item hidden"> %>
          <%# <a class="nav-link active" aria-current="page" href="#">About</a> %>
        <%# <%= link_to 'About Us', home_about_path, class:"nav-link" %>

        <%# </li> %>
    <div class="logo" >
      <%# <div class="nav-item"> %>
        <%# link_to home_our_mission_url do %>
          <%# image_tag("mission.png", alt: 'Logo',class: 'te')%>
        <%# end %>    
      <%= link_to home_our_mission_url, class:'nav-icon' do %>
        <%= image_tag("icons/wall-outline-64x64.png", class:'
      nav-icon', alt: "mission-icon", size: '', :style => "padding: 0px 0px; margin: auto;") %>
      <% end %>
      <%= link_to 'Our mission', home_our_mission_url, class:"link-text logo-text"%>
          <%# </div> %>
    </div>
    <div class="logo">
      <a class="nav-item">
          <%# <%= link_to 'Contact Us', contact_us class:"nav-link"%> 
          <%# <a href="tel:13432212" id=""  %>
          <%# > %>
        <%= image_tag("icons/phone-call.png", class:'nav-icon',alt: "call-now", size: '64', :style => "padding: 0px 0px; margin: auto;") %>
          <h4 class="link-text logo-text">
          Contact</h4>
      </a>
    </div>
        
    <div class="logo">
      <%= link_to home_our_mission_url do %>
        <a href="email:SeguraConstruction Co"  id="" class="nav-item" > 
          <%= image_tag("icons/phone-message.png", class:'nav-icon', alt: "phone-icon", size: "64x64", :style => "padding: 0px 0px; margin: auto;margin-left: 10px;") %> 
        </a>
        <h4 class="logo-text">email us </h4>
      <% end %>
    </div>
    <% if user_signed_in?%>
        <!--<li class="nav-item">
          <%= link_to 'dashboard', 'dashboard/index', class:"nav-link" %>
        </li> -->
      <% if current_user.admin %>
        <li class="nav-item ">
          <%# <a class="nav-link" href="#">Features</a> %>
          <%= link_to 'see users', users_index_path, class:"nav-link " %>
        </li>
        <% end %>
        <li class="nav-item ">
          <svg class="nav-icon"></svg>
          <%= link_to 'Dashboard', dashboard_index_path, class:"nav-link" %>
        </li>
      
        <li class="nav-item">
          <%= link_to edit_user_registration_path image_tag("icon/edit-user-icon.png", class:'nav-icon nav-link', alt: "edit-user-icon", size: '', :style => "padding: 0px 0px; margin: auto;")%>
          <%#% link_to 'Edit Profile', edit_user_registration_path,class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Logout', destroy_user_session_path, method:"delete", class:"nav-link d-desktop", id: "logout" %>
        </li>
        <% else %>
        <li class="">
          <%= link_to 'Log In', new_user_session_path, class:"nav-link"%>
        </li>
        <% end %>
        <%# <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li> %>
        <%# <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li> %>
      </ul>
  <%# </div> %>
</nav>
 <%# <%else%> 
 <%# <%end  

app/views/shared/_login.html.erb
<h2 class="center">Log in</h2>

<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <% f.label :email %><br />
    <%= f.email_field :email, autofocus: true, placeholder:"email", autocomplete: "email" %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "current-password" %>
  </div>

  <% if devise_mapping.rememberable? %>
    <div class="field" id="user_remember_me">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

app/views/shared/_sidenav.html.erb
<header class="main-head h-[80px] md:h-[100vh] z-10 w-full md:w-1/6 lg:w-[12%] bg-gray-700 dark:bg-gray-900 px-2 text-center fixed bottom-0 pt-8 md:pt-8 md:top-0 md:left-0 md:overflow-y-scroll md:border-r-4 md:border-gray-600 justify-items-center" style="padding-top: 1rem;">
  <nav class="md:relative mx-auto h-[100%] lg:float-right lg:px-6">
      <ul class="list-reset flex h-[100%] flex-row md:flex-col text-center place-items-center md:text-left" style="text-align:center">
        <li class=" flex-1 hidden md:block">
          <a href="<%= root_path %>
          " class="block py-1 md:py-3 pl-1 align-middle text-gray-800 no-underline hover:text-blue-500 border-b-2 border-gray-200 dark:border-gray-800  hover:border-blue-500">  
            <%= image_tag("logo/logo-icon-80x40.png", alt: "My logo", class: 'fas fa-link h-[50px] md:h-[unset] pr-0 md:pr-3 pb-1 md:pb-0 text-xs md:text-base text-gray-600 md:text-gray-400 block md:inline-block', size: '75x75', :style => "padding-bottom: ;") %>

              <%# image_tag("logo/final-logos-nobg/logo-title-straight-black-red-nobg.png", alt: "Segura & Co Logo", class: '', :style => "padding: 0px 0px;") %>
          </a>    
        </li>
        <% if !user_signed_in? %>
        <li class=" flex-1">      
            <%= link_to new_user_session_path do %>
              <%= image_tag("icons/sign-in-64x64.png", class:"m-auto h-[50px] md:h-[unset] block py-1 md:py-3 pl-1 align-middle text-gray-800 no-underline hover:text-pink-500 border-b-2 border-gray-200 dark:border-gray-800 hover:border-blue-500 fas fa-link pr-0 md:pr-3" , alt:"sign-in icon" ) %>
              <h4 class="pb-1 md:pb-0 text-xs md:text-base text-gray-300 dark:text-gray-200 block md:inline-block">Log In </h4>
              <%# link_to 'Log In', new_user_path, class:"nav-link" %>
            <% end %>
          </li>
          <%end  %>
          <%#  <li class=" flex-1">
                     <a href="#" class="block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-pink-600">
                     <i class="fas fa-link pr-0 md:pr-3 text-pink-500"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-white md:font-bold block md:inline-block">Active Link</span>
                     </a>
                  </li> %>
          <% if user_signed_in? %>
            <li class=" flex-1 hover:text-blue-400">   
              <%= link_to destroy_user_session_path, method: :delete do %>
              <%# link_to 'Logout', destroy_user_session_path, method:"delete" do %>
                <%= image_tag("icons/log-out-64x64", class:"h-[50px] md:h-[unset] m-auto block py-1 md:py-3 pl-1 align-middle text-white no-underline hover:text-white border-b-2 border-gray-200 dark:border-gray-800 fas fa-link pr-0 md:pr-3 text-pink-500" , alt:"logout icon", ) %>
                <h4  class="pb-1 md:pb-0 text-xs md:text-base text-gray-400 dark:text-gray-200 md:font-bold block md:inline-block">Log out</h4>  
              <% end %>
          
            </li>
         <% if  current_user.admin  %>
              <li>
                  <%= link_to '/admin' do %>
                    <%= image_tag("icons/clients-64x64.png", class:"h-[50px] md:h-[unset] sidebar-icon m-auto" , alt:"dashboard icon") %>
                    <h4  class="pb-1 md:pb-0 text-xs md:text-base text-gray-400 dark:text-gray-200 block md:inline-block"> Admin Dashboard</h4>
                    <%# link_to 'see users', users_index_path, class:"nav-link " %>
                  <% end %>
              </li>
              <% else %>
                   <li>

              <%= link_to dashboard_index_path, class:'' do %>
        
                <%= image_tag("icons/blueprint-blue-64x64.png", class:"h-[50px] md:h-[unset] sidebar-icon m-auto border-b-2 border-gray-200 dark:border-gray-800 hover:border-blue-500" , alt:"dashboard icon", ) %>
                <h4  class="pb-1 md:pb-0 text-xs md:text-base text-gray-400 dark:text-gray-200 block md:inline-block">Dashboard</h4>
              <% end %>       
            </li>
              <% end %>


              <% if current_page?('/dashboard') %>
                <li class=" flex-1">   
                <%= link_to edit_user_registration_path,class:"h-[50px] md:h-[unset] block py-1 md:py-3 pl-1 align-middle text-gray-800 no-underline hover:text-blue-500 border-b-2 border-gray-200 dark:border-gray-800  hover:border-pink-500" do %>
                  <%= image_tag 'icons/settings-64x64.png', class: 'fas fa-link pr-0 md:pr-3 m-auto', size: '' %>
                  <h4 class="pb-1 md:pb-0 text-xs md:text-base text-gray-400 dark:text-gray-200 block md:inline-block">Edit Profile</h4>  
                <% end %>
                </li>
              <% end %>
          <% end %>     
         

         
          <li class=" flex-1">
            <%= link_to home_our_mission_url, class:'block py-1 md:py-3 pl-1 align-middle text-gray-800 no-underline hover:text-blue-500' do %>
              <%= image_tag("icons/concrete-color-soft-64x64.png", class:'
              fas fa-link m-auto h-[50px] md:h-[unset] border-b-2 border-gray-200 dark:border-gray-800 hover:border-blue-500', alt: "mission-icon", size: '', :style => "") %>
              <h4  class="pb-1 md:pb-0 text-xs md:text-base text-gray-300 dark:text-gray-200 block md:inline-block">Our Mission</h4>
              <%# link_to 'Our mission', home_our_mission_url, class:"nav-link", style: ""%>
            <% end %>
          </li>  
          <li class="flex-1 md:hidden">
            <%= link_to root_path, class:'inline-flex block py-1 md:py-3 pl-1 align-middle text-gray-800 no-underline hover:text-blue-500 border-b-2 border-blue-500 hover:border-blue-700' do %>
              <%= image_tag("logo/logo-icon-50x50.png", class:'h-[50px] md:h-[unset] fas fa-link pr-0 md:pr-3 m-auto', alt: "segura & company logo", size: '', :style => "") %>
            <% end %>
          </li>  
          <li class=" flex-1">   
            <a href="tel:5017772525" class="block py-1 md:py-3 pl-1 align-middle text-gray-300 dark:text-gray-200 no-underline ">
              <%= image_tag("icons/phone-call.png", class:'fas fa-link pr-0 md:pr-3 m-auto h-[50px] md:h-[unset] border-b-2 border-gray-200 dark:border-gray-800 hover:border-blue-500', alt: "call/text now", size:"" , :style => "") %>

              <h4  class="pb-1 md:pb-0 text-xs md:text-base text-inherit block md:inline-block text-gray-400 dark:text-gray-200">
              Call/Text
              </h4>
            </a>      
          </li>
          <li class=" flex-1">
            <%# link_to home_our_mission_url, class:'' do %>
            <a class="block py-1 md:py-3 pl-1 align-middle text-gray-400 dark:text-gray-200 no-underline" href="mailto:project@seguraconstruction.com">
              <%= image_tag("icons/email-send-64x64.png", class:'
            fas fa-link pr-0 md:pr-3 m-auto h-[50px] md:h-[unset] border-b-2 border-gray-200 dark:border-gray-800 hover:border-blue-500', alt: "email-icon", size: '', :style => "") %>
            
            <h4  class="pb-1 md:pb-0 text-xs md:text-base text-inherit block md:inline-block text-gray-400 dark:text-gray-200">Email </h4>
            </a>
          </li>   
        <%# <li class=" flex-1 hidden">
            <a href="#" class="block py-1 md:py-3 pl-1 align-middle text-gray-800 no-underline hover:text-blue-500 border-b-2 border-gray-200 dark:border-gray-800 hover:border-blue-500 ">
            <i class="fas fa-link pr-0 md:pr-3"></i><span class="pb-1 md:pb-0 text-xs md:text-base text-gray-600 text-inherit block md:inline-block">Link</span>
            </a>
        </li> %>
      </ul>
  </nav>
</header>


<script>
  // helper function t0 add styles to element
  function css(element, style) {
      for (const property in style)
          element.style[property] = style[property];
  }

  /*

  const note = document.querySelector('.note');
  css(note, {
      'background-color': 'yellow',
      color: 'red'
  });

  */
  // function changeColor() {
  //     this.classList.toggle('red');
  //     this.classList.toggle('green');
  // }

  //  document.querySelector('#btn').addEventListener('mouseenter', changeColor);
  //  document.querySelector('#btn').addEventListener('mouseleave', changeColor );

  var sidenav = document.querySelector(".main-head");

  function toggleSidenav() {

    // var firstP = document.getElementById("firstParagraph");
    sidenav.id? sidenav.removeAttribute('id'): sidenav.setAttribute("id","widenav");
      sidenav.id? console.log('id was set') : console.log('id was removed');
      console.log(sidenav.id);


  // firstP.id="newPracPara";
  // console.log(document.getElementById("newPracPara").id);
    // document.getElementById('formId').submit();
  }
  sidenav.addEventListener('click', toggleSidenav);

 
</script>