config/routes.rb
Rails.application.routes.draw do
  # root 'public#index'
  # devise_for :users
  root 'home#index'
  # get 'home/index'
  get 'home/videos'
  get 'home/careers'
  # , to: 'home#about'
  get 'home/our_mission'
  get 'home/gallery'
  
  # get 'careers/new'

  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    confirmations: 'devise/confirmations', sign_up_create: 'home'
  }
  
  # to verride registrations controller 
  # devise_for :users, controllers: {registrations: 'users/registrations',
  #   confirmations: 'devise/confirmations', sign_up_create: 'home'
  # }
  resources :dashboard
  resources :home, only: [:index, :our_mission, :about]
  
  resources :user do 
   resources :project 
  end
  

  resources :careers, :only => [:show, :new, :create]
  
devise_scope :user do
  get "/users/sign_out" => "devise/sessions#destroy"
end
  # get 'users/sign_out', to: 'devise/sessions#destroy'

  # post "/dashboard", to: "sign_up_create#update"


  #not using /users route
  # get '/users', to: 'users#index'
  # devise_for :users, controllers: {sessions: 'devise/sessions', users: 'users'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  #  list of users ?
  # get 'users#sign_up'
  # get 'users#sign_in'
  # get '/'
  # get '/sign'
  # get 'devise/sessions#new'
  # get '/users/sign_up'

  # new devise registrations//missing controller?
  # registration page route?
  # get 'devise/registrations/index'

  # get 'devise/registrations#new'
  # (.:format) 
  # get 'dashboard/index'
  # post 'dashboard/index'

  # get '/dashboard/new'
  # get 'dashboard/show'
  # get 'dashboard/edit'
  # post 'dashboard/create'
  # post 'dashboard/update',  to 'dashboard#update'

  # not using users page
  # get 'users/index'

  resources :sign_up_create
  
  # post "/signupcreate", to: "sign_up_create#create"

  # resdaer
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # root 'dashboard#index'
  


# get '/users/:user', to: 'devise/sessions#sign_in', as: 'user'

# get '/users/:user', to: 'devise/sessions#destroy'
# , as: 'user'

# resource :users
# unauthenticated do
  # root to: "home#index"
# end
# authenticated do 
  # root :to => 'dashboard#index'
# end

# as :user do
  # get 'sign_in', :to => 'devise/sessions#new'
  # get 'sign_out', :to => 'devise/sessions#destroy'
# end

#  get '/users/:username', to: 'sessions#show' 
#  get '/users/:username', to: 'sessions#show', as: 'user'
# controllers {sessionsController}
# get '/users/new' controllers { sessionsController}
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
   def index
    @user ||= User.new 
    @project ||= Project.new
    
    # @user = Person.new
    @user.projects.build
  end

  def our_mission 
    

  end

  def about 

  end
  private 


  helper_method :resource_name, :resource, :devise_mapping, :resource_class

  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/gallery.html.erb
<section class="gallery md:pl-[20%] lg:pl-[15%] flex flex-col pl-10 pr-10 bg-transparent text-white">
  <div class="max-w-screen-xl px-4 py-8 sm:py-12 sm:px-6 lg:py-16 lg:px-8 flex flex-col items-center justify-center">
    <div class="max-w-xl">
      <h2 class="mt-5 mb-2 text-center text-lg md:text-xl lg:text-2xl font-bold">Project Gallery</h2>
       <div id="fullpage" onclick="this.style.display='none';" class="z-10 h-full w-auto"></div>

      <p class="mt-4 text-gray-300 text-center">
        Projects at differents stages of completion.
      </p>
    </div>

    <div
      class="mt-8 grid grid-cols-1 gap-8 md:mt-16 md:grid-cols-2 md:gap-12 lg:grid-cols-3">
      <div class="flex items-start gap-4">
        <span class="hidden shrink-0 rounded-lg bg-gray-800 p-4">
          <svg
            class="h-5 w-5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M12 14l9-5-9-5-9 5 9 5z"></path>
            <path
              d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z"
            ></path>
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222"
            ></path>
          </svg>
        </span>

        <div>
          <h2 class="mt-5 mb-2 text-lg md:text-xl lg:text-2xl font-bold text-center" >Lake House Foundation Wall</h2>
        <div style="" class="rounded-xl">
            <%= image_tag('wall-lake-straight.png', id:"toggle-fullscreen", class:"rounded-xl", alt: 'Lake Foundation wall')%>
        </div>
        <h4 class="text-center text-gray-200 mt-2">completed</h4>
        </div>
      </div>

      <div class="flex items-start gap-4">
        <span class="hidden shrink-0 rounded-lg bg-gray-800 p-4">
          <svg
            class="h-5 w-5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M12 14l9-5-9-5-9 5 9 5z"></path>
            <path
              d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z"
            ></path>
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222"
            ></path>
          </svg>
        </span>

        <div>
          <h2 class="mt-5 mb-2 text-lg md:text-xl lg:text-2xl font-bold text-center" style="">Rebar Reinforcement</h2>
          <div style="" class="project-cont">
            <%= image_tag('retaining-wall-rebars.png', id:"toggle-fullscreen", class:"rounded-xl", alt: 'Rebar Reinforcements inside set forms')%>
          </div>
           <h4 class="text-center text-gray-200 mt-2">Installing steel rebar reinforcements</h4>
        </div>
      </div>

      <div class="flex items-start gap-4">
        <span class="hidden shrink-0 rounded-lg bg-gray-800 p-4">
          <svg
            class="h-5 w-5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M12 14l9-5-9-5-9 5 9 5z"></path>
            <path
              d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z"
            ></path>
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222"
            ></path>
          </svg>
        </span>

        <div>
          <h2 class="mt-5 mb-2 text-lg md:text-xl lg:text-2xl font-bold text-center" >Project Basement Walls</h2>
          <div style="" class="project-cont">
            <%= image_tag('retaining-wall-outside-tall.png', id:"toggle-fullscreen", class:"rounded-xl",alt: 'Tall wall project')%>
          </div>
          <h4 class="text-center text-gray-200 mt-2">Installing inside forms before pouring</h4>
        </div>
      </div>

      <div class="flex items-start gap-4">
        <span class="hidden shrink-0 rounded-lg bg-gray-800 p-4">
          <svg
            class="h-5 w-5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M12 14l9-5-9-5-9 5 9 5z"></path>
            <path
              d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z"
            ></path>
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222"
            ></path>
          </svg>
        </span>

        <div>
          <h2 class="mt-5 mb-2 text-lg md:text-xl lg:text-2xl font-boldtext-center" >Project Featuring Tall Walls</h2>
          <div style="" class="project-cont">
            <%= image_tag('retaining-wall-straight.png', class:"rounded-xl",alt: 'Straight Retaining wall')%>
             <h4 class="text-center mt-2 text-gray-200">14 ft height </h4>
        </div>
        </div>
      </div>

      <div class="flex items-start gap-4">
        <span class="hidden shrink-0 rounded-lg bg-gray-800 p-4">
          <svg
            class="h-5 w-5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M12 14l9-5-9-5-9 5 9 5z"></path>
            <path
              d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z"
            ></path>
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222"
            ></path>
          </svg>
        </span>

        <div>
          <h2 class="mt-5 mb-2 text-lg md:text-xl lg:text-2xl font-bold text-center">Poured Wall Corner</h2>
          <div style="" class="project-cont">
            <%= image_tag('retaining-wall-corner-nobg.png', class:"rounded-xl",alt: 'Retaining Wall Corner Poured')%>
          </div>
           <h4 class="text-center mt-2 text-gray-200">Poured ready for stripping</h4>
        </div>
      </div>

      <div class="flex items-start gap-4">
        <span class="hidden shrink-0 rounded-lg bg-gray-800 p-4">
          <svg
            class="h-5 w-5"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M12 14l9-5-9-5-9 5 9 5z"></path>
            <path
              d="M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z"
            ></path>
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M12 14l9-5-9-5-9 5 9 5zm0 0l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14zm-4 6v-7.5l4-2.222"
            ></path>
          </svg>
        </span>

        <div>
          <h2 class="mt-5 mb-2 text-lg md:text-xl lg:text-2xl font-bold text-center" >Curved Design</h2>
          <div style="" class="project-cont">
            <%= image_tag('retaining-wall-curved.png', id:"toggle-fullscreen", class:"rounded-xl",alt: 'Tall wall project')%>
          </div>
          <h4 class="text-center mt-2 text-gray-200">12 ft height </h4>
        </div>
      </div>
    </div>
    <span class="hidden mt-20 text-blue-500">
    <%#= link_to home_videos_url %>
    </span>
  </div>
</section>
<script>
const imgs = document.querySelectorAll(".gallery img");
console.log(imgs);
const fullPage = document.querySelector("#fullpage");
console.log('fullPage', fullPage)
imgs.forEach((img) => {
  console.log('img', img)
  img.addEventListener("click", function () {
    console.log('img clicked', img)
    fullPage.style.backgroundImage = "url(" + img.src + ")";
    fullPage.style.display = "block";
    fullPage.style.display = "static";
  });
});

</script>
<style>
#fullpage {
  display: none;
  position: fixed;
  z-index: 9999;
  top: 0;
  left: 0;
  overflow: hidden;
  width: 100vw;
  height: 100vh;
  background-size: contain;
  background-repeat: no-repeat no-repeat;
  background-position: center center;
  background-color: black;
}
.project-cont {
  overflow-x: scroll;
  /* min-height: 150px; */
  /* min-width: 150px; */
  width: 100%;
  margin-left: auto;
  margin-right: auto;
  text-align: center;
  /* display: table-cell; */
  vertical-align: middle;
}
.project-cont > img {
  width: 100%;
}
</style>

app/views/home/our_mission.html.erb
<div class="md:pl-[17%] lg:pl-[12%] flex flex-col md:flex-row md:mt-32 h-[80%]" style="">
  <div class="md:w-[50%] ">
    <%= image_tag("no-bg-elements/forms.png", alt: "My logo", size: '200x300', :style => "padding: 60px 20px; margin: auto;filter: invert(1);") %>

  </div>
  <div class="flex flex-col text-center md:w-[50%] px-10 md:items-center md:justify-center" style="">
      <h2 class="text-gray-100 dark:text-gray-400 text-2xl">Family owned and operated<br><span class="text-blue-500 text-3xl">Driven</span> by <span class="text-red-500 text-3xl">Heart</span></h2>
      <p class="text-slate-200 dark:text-gray-400 text-xl text-center" id="">SEGURA & Company provides the highest quality contruction services focusing on Poured-in-Place Reinforced Concrete Retaining Walls</p>
      <p class="text-gray-300 text-xl">Our expertise is unparalled</p>
  </div>
    
</div>

app/views/home/videos.html.erb
<%# about.html.erb %>
<section class="md:pl-[20%] lg:pl-[15%] flex flex-col pl-10 bg-transparent text-white">
  <div class="max-w-screen-xl px-4 py-8 sm:py-12 sm:px-6 lg:py-16 lg:px-8 flex flex-col items-center justify-center">
    <div class="max-w-xl">
      <h2 class="mt-5 mb-2 text-center text-lg md:text-xl lg:text-2xl font-bold">The Construction Process</h2>
       <div id="fullpage" onclick="this.style.display='none';" class="z-10 h-full w-auto"></div>

      <p class="mt-4 text-gray-300 text-center">
        Reinforced Concrete Construction
      </p>
    </div>
    <div
      class="mt-8 grid grid-cols-1 gap-8 md:mt-16 md:grid-cols-2 md:gap-12">
         <div class="flex justify-center gap-4">
          <div class="flex flex-col w-[100%] self-center justify-center align-middle place-self-center">
            <h2 class="mt-5 mb-2 text-lg md:text-xl lg:text-2xl font-bold text-center" >Retaining Wall Construction</h2>
            <div style="" class="rounded-xl w-[100%]">
              <iframe class="" width="100%"  height="415" src="https://www.youtube.com/embed/930bJd9juGU" title="Reinforced Concrete Retaining Wall Buld Video" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
          </div>
        </div>
         <div class="flex justify-center gap-4">
          <div class="flex flex-col w-[100%] self-center justify-center align-middle place-self-center">
            <h2 class="mt-5 mb-2 text-lg md:text-xl lg:text-2xl font-bold text-center" >Steel-Ply Formation System</h2>
            <div style="" class="rounded-xl w-[100%]">
              <iframe class="" width="100%"  height="415" src="https://www.youtube.com/embed/LCmVTpCID1c" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
          </div>
        </div>
        <div class="flex justify-center gap-4">
          <div class="flex flex-col w-[100%] self-center justify-center align-middle place-self-center">
            <h2 class="mt-5 mb-2 text-lg md:text-xl lg:text-2xl font-bold text-center" >Pouring a House: Reinforced Concrete Walls</h2>
            <div style="" class="rounded-xl w-[100%]">
              <iframe class="" width="100%" height="415" src="https://www.youtube.com/embed/Ms5NTs4_Y5Y" title="Pouring House Reinforced Concrete Walls" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
          </div>
        </div>
        <div class="flex justify-center gap-4">
          <div class="flex flex-col w-[100%] self-center justify-center align-middle place-self-center">
            <h2 class="mt-5 mb-2 text-lg md:text-xl lg:text-2xl font-bold text-center" >Forming long curved retaining wall</h2>
            <div style="" class="rounded-xl w-[100%]">
              <iframe class="" width="100%"  height="415" src="https://www.youtube.com/embed/stSUH7hdEuc" title="Example Finished Commercial Retaining Wall On Footer Pouring Video" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
          </div>
        </div>
        <div class="hidden justify-center gap-4">
          <div class="flex flex-col w-[100%] self-center justify-center align-middle place-self-center">
            <h2 class="mt-5 mb-2 text-lg md:text-xl lg:text-2xl font-bold text-center" > Retaining Wall Construction Animation</h2>
            <div style="" class="rounded-xl w-[100%]">
              <iframe class="" width="100%"  height="415" src="https://www.youtube.com/embed/y1pAGIf8v2c" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
          </div>
        </div>
        <div class="flex justify-center gap-4">
          <div class="flex flex-col w-[100%] self-center justify-center align-middle place-self-center">
            <h2 class="mt-5 mb-2 text-lg md:text-xl lg:text-2xl font-bold text-center" > Forming Tall Retaining Walls</h2>
            <div style="" class="rounded-xl w-[100%]">
              <iframe class="" width="100%" height="415" src="https://www.youtube.com/embed/NdIx7Vm_3xs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
          </div>
        </div>
        <div class="flex justify-center gap-4">
          <div class="flex flex-col w-[100%] self-center justify-center align-middle place-self-center">
            <h2 class="mt-5 mb-2 text-lg md:text-xl lg:text-2xl font-bold text-center" >   Pouring the Footer </h2>
            <div style="" class="rounded-xl w-[100%]">
              <iframe class="" width="100%" height="415" src="https://www.youtube.com/embed/pMxGexmQe9A" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>